### ISSUE TITLE
Produce Exec Option vs. Argument, update README

### ISSUE THREAD

**Issue by itehle** [bfonta/bye_splits#14]
[This](https://github.com/bfonta/bye_splits/blob/1288a7c3a6f36a786ba4c217ced44e70f88f2404/bye_splits/production/produce.cc#L81) suggests that the line ```./produce electrons``` in the [README](https://github.com/bfonta/bye_splits/blob/main/README.org?#L49) should be changed to ```./produce.exe --particles electrons```

**Comment by bfonta** [comment]
No doubt. It will be included with #10, which should be merged relatively soon.
