### ISSUE TITLE
Extreme Lag When Loading Pile Up Data

### ISSUE THREAD

**Issue by isehle** [bfonta/bye_splits#29]
The method used to read in the data here, notably using uproot's ```tree.arrays()``` method, is unable to handle the trigger cell data when pile up is included. Indeed even selecting just 10 events lags for over thirty minutes (and I aborted before it finished). We'll need to find another way of reading in the data.

https://github.com/bfonta/bye_splits/blob/396555886669ed3747d55897bfd0c6c3e3cbd31c/bye_splits/data_handle/event.py#L154

**Comment by bfonta** [comment]
@isehle I suppose this is already fixed by #44.
