### ISSUE TITLE
`df` referenced without assignment

### ISSUE THREAD

**Issue by isehle** [bfonta/bye_splits#40]
This should likely be ```df_gen``` instead of `df`

https://github.com/bfonta/bye_splits/blob/c115c2076ac99c290c2cc1cb6d6bd34c96f2316b/bye_splits/data_handle/data_process.py#L28

**Comment by bfonta** [comment]
Thanks for pointing it out. It should actually be ```data```.

**Comment by isehle** [comment]
Ah yes makes sense.
